### PR TITLE
add new Multiple log WriterEntry. Closes #32

### LINKED ISSUE #32: MultiWriter based on io.Writer
Sometimes I need to write to different outputs with a selected level. 
For example, given a Debug level I would like to be able to write to console, log file and syslog. 

Have tried `io.MultiWriter` but `ConsoleWriter` does not implement `io.Writer` method. 

Alternatively we could implement something like https://github.com/rs/zerolog/blob/117cb53bc66413d9a810ebed32383e53416347e3/writer.go#L88

I have tried several things and the only option I see is `MultiWriter` but it's level based not `io.Writer` based.

Any suggestions?

### PR DESCRIPTION
**Pull request by ogimenezb**

### CODE REVIEW

**Comment by phuslu** [comment]
thanks, LGTM except the writer naming, can we name it to "MultiEntryWriter" ? Because other writer names share the "Writer" suffix.

**Comment by ogimenezb** [comment]
Ok, file name is OK?

**Comment by ogimenezb** [comment]
Done, it you need something else please let me know.

**Comment by phuslu** [comment]
thanks a lot!

**Comment by ogimenezb** [comment]
your welcome, happy to incorporate new features.

**Pull request merged**
