### PR TITLE
Switch to allow header timestamps to be UTC

### PR DESCRIPTION
**Pull request by fireflycons**
Perhaps I'm missing something, but I could not see how to get the header timestamp to be always UTC instead of system local time.

This PR adds a boolean field to `Logger` so that UTC may be enabled, and the logic for this in `header()`

Additionally fix a typo in `Logger` comments and disable running of syslog tests on Windows.

### CODE REVIEW

**Comment by phuslu** [comment]
thanks! will go through it today!

**Comment by fireflycons** [comment]
Out of interest, what reference did you use to craft the ASM to get the go-id?

**Comment by phuslu** [comment]
I added comment to `goid.s`, using asm to impalement this function can minimalized the function call overhead in go, I think.

**Comment by phuslu** [comment]
After consideration I thin it's no problem for adding the "TimeUTC" field.
1. Is there a better name for it? (If currently no, let us merge it first)
2. Maybe the code change could be simplify/tidy. (maybe I'm wrong, but it will be a blocker)

**Comment by phuslu** [comment]
Let me merge it first, thanks.

**Comment by phuslu** [comment]
chatgpt suggested below names

1. EnforceUTC
2. ForceUTC
3. TimeEnforceUTC
4. TimeForceUTC
5. TimeFormatUTC

**Comment by phuslu** [comment]
Another option is change `TimeUTC bool` to `TimeLocation *time.Location`.

If user give a non-nil value(e.g. Time.UTC), we will call [Time.In](https://pkg.go.dev/time?utm_source=godoc#Time.In) for the timestamp, and we also need implement a fast path for time.UTC.

**Comment by phuslu** [comment]
@fireflycons please take a look this approach https://github.com/phuslu/log/pull/66 if you have time, thanks.

**Pull request merged**
