### PR TITLE
feat: support long filename and line number

### PR DESCRIPTION
**Pull request by u2386**

### CODE REVIEW

**Comment by phuslu** [comment]
thanks, will look soon.

**Comment by phuslu** [comment]
thanks, I merged. But I would like change
```go
	// Fullpath determines whether to use full file path like /a/b/c/d.go:line as "caller" or not.
	Fullpath bool
```
to other name, E.g. `FullpathCaller`, do you have any suggestion/option?

**Comment by u2386** [comment]
I think `FullpathCaller` is clearer.

**Comment by phuslu** [comment]
thanks, I renamed it to `FullpathCaller`

**Pull request merged**
