### PR TITLE
added GrcpGatewayLogger that implements grpc-middleware

### PR DESCRIPTION
**Pull request by ogimenezb**
Example included in readme.

It should be good to go.

### CODE REVIEW

**Comment by ogimenezb** [comment]
Once you have revised it and committed can you please tag it so I can make pull request to grpc-ecosystem

**Comment by phuslu** [comment]
> Once you have revised it and committed can you please tag it so I can make pull request to grpc-ecosystem
Sure

**Comment by ogimenezb** [comment]
Ready to make pull request to grpc-ecosystem, let me know once you create a new tag so I can make a clean request with a correct go.mod

**Comment by phuslu** [comment]
sorry for busy state today, I will tag it ASAP

**Comment by ogimenezb** [comment]
no problem, we all have busy days, take your time.

**Comment by phuslu** [comment]
I tagged v1.0.72, thanks for your help and patient.

**Comment by ogimenezb** [comment]
Thanks!!!
Made the pull request: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/425
Hope CLA is OK

**Comment by ogimenezb** [comment]
I has been merged as a new log provider go-grpc-middleware for v2.

**Comment by phuslu** [comment]
oh, many thanks!

**Pull request merged**
